### ISSUE TITLE
Không hiển thị cổng thanh toán paypal

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-wallet#2]
Khi mình mua 1 ứng dụng tại https://nukeviet.vn/vi/store/ Thì nó chỉ thanh toán bằng vnpay chứ ko hiên thị   paypal

**Comment by hoaquynhtim99** [comment]
Hiện tại thì wallet chưa phát triển tính năng quy đổi tiền => Thanh toán cho nên ứng dụng có tiền VNĐ chỉ thanh toán được = VNPAY
Ứng dụng =USD chỉ thanh toán được = PayPal 
Cái này theo cấu hình của cổng thanh toán.
Trong tương lai cần phát triển thêm tính năng

**Comment by vuthao** [comment]
@hoaquynhtim99 cái này chắc chắn sẽ phải nghiên cứu để tự động chuyển đổi đơn vị tiền tệ để dùng được cả hai cổng thanh toán.

**Comment by hoaquynhtim99** [comment]
@vuthao vâng anh, trong thời gian tới em sẽ tiếp tục thêm mấy tính năng đó vào. Store lúc trước có nhưng mà do khác nhau nhiều thứ quá chưa chuyển được sang wallet

**Comment by hoaquynhtim99** [comment]
Đã thêm tại https://github.com/nukeviet/module-wallet/commit/298cebb9055e06d89eb5c177ff961c2a40aaaaa8
