### ISSUE TITLE
Thanh toán VNPAY, báo hệ thống không cập nhật được giao dịch

### ISSUE THREAD

**Issue by mynukeviet** [nukeviet/module-wallet#6]
Mình đang test thanh toán qua VNPAY, thanh toán xong bên VNPAY báo Thành công, nhưng khi return về site thì thông báo như bên dưới.

Đọc code thấy có nói `Việc cập nhật do IPN đảm nhiệm`, không biết còn thiếu sót cấu hình nào không?

![image](https://user-images.githubusercontent.com/6407361/49692366-aca01b80-fb8b-11e8-90b2-3ba3a032a977.png)

**Comment by vuthao** [comment]
> Đọc code thấy có nói Việc cập nhật do IPN đảm nhiệm
>
Cần liên hệ với VNPAY để cấu hình.

>

**Comment by mynukeviet** [comment]
Dạ, cảm ơn anh Thảo
